export const imagedata = [
    {
        "id":1,
        "url":"/default/0.jpg"
    },
    {
        "id":2,
        "url":"/default/1.jpg"
    },
    {
        "id":3,
        "url":"/default/2.jpg"
    },
    {
        "id":4,
        "url":"/default/3.jpg"
    },
    {
        "id":5,
        "url":"/default/4.jpg"
    },
    {
        "id":6,
        "url":"/default/5.jpg"
    },
    {
        "id":7,
        "url":"/default/6.jpg"
    },
    {
        "id":8,
        "url":"/default/7.jpg"
    },
    {
        "id":9,
        "url":"/default/8.jpg"
    },
    {
        "id":10,
        "url":"/default/9.jpg"
    },
    {
        "id":11,
        "url":"/default/10.jpg"
    },
    {
        "id":12,
        "url":"/default/11.jpg"
    },
    {
        "id":13,
        "url":"/default/12.jpg"
    },
    {
        "id":14,
        "url":"/default/13.jpg"
    },
    {
        "id":15,
        "url":"/default/14.jpg"
    },
    {
        "id":16,
        "url":"/default/15.jpg"
    },
    {
        "id":17,
        "url":"/default/16.jpg"
    },
]